---
- name: Playing with Ansible Cisco IOS Modules
  hosts: all

  tasks :

  - name: Gather facts from Switch 
    ios_facts:
     gather_subset: all
    register: ios_facts

  # - debug:
  #    var: ios_facts
     
  - name: Merge playbook config with device config
    ios_vlans:
     config: 
     - name: VLAN49
       vlan_id: 49
       shutdown: disabled
     - name: VLAN50
       vlan_id: 50
       shutdown: disabled
     - name: VLAN51
       vlan_id: 51
       shutdown: disabled
     - name: VLAN52
       vlan_id: 52
       shutdown: disabled
     - name: VLAN53
       vlan_id: 53
       shutdown: disabled
     - name: VLAN54
       vlan_id: 54
       shutdown: disabled
     - name: VLAN55
       vlan_id: 55
       shutdown: disabled

  - name: Ensure interface is configured as trunk with allowed vlans and native to vlan
    ios_l2_interface:
     name: "{{ item }}"
     mode: trunk
     native_vlan: "49"
     trunk_allowed_vlans: "49"
    with_items :
    - GigabitEthernet0/1
    - GigabitEthernet0/2
    - GigabitEthernet0/3
    - GigabitEthernet0/4

  - name: Ensure interface is configured as trunk with allowed vlans and native to vlan
    ios_l2_interface:
     name: "{{ item }}"
     mode: trunk
     native_vlan: "50"
     trunk_allowed_vlans: "50-55"
    with_items :
    - GigabitEthernet0/5
    - GigabitEthernet0/6
    - GigabitEthernet0/7
    - GigabitEthernet0/8
    - GigabitEthernet0/9
    - GigabitEthernet0/10
    - GigabitEthernet0/11
    - GigabitEthernet0/12
    - GigabitEthernet0/13
    - GigabitEthernet0/14
    - GigabitEthernet0/15
    - GigabitEthernet0/16
    - GigabitEthernet0/17
    - GigabitEthernet0/18
    - GigabitEthernet0/19
    - GigabitEthernet0/20

  - name: Ensure GigabitEthernet21-24 is configured as trunk with allowed vlan 1,50-55 and set native to 1
    ios_l2_interface:
     name: "{{ item }}"
     mode: trunk
     native_vlan: "1"
     trunk_allowed_vlans: "1,49-55"
    with_items :
    - GigabitEthernet0/21
    - GigabitEthernet0/22
    - GigabitEthernet0/23
    - GigabitEthernet0/24

  - name: save running to startup always
    ios_config:
     save_when: always
